# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Juges (2 juges dans une organisation)
  # ---------------------------------------------------------------------------
  - Name: Juges
    Domain: juges.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: Juge1  # Peer représentant le Juge 1
        SANS:
          - localhost
      - Hostname: Juge2  # Peer représentant le Juge 2
        SANS:
          - localhost
    Users:
      Count: 2  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # Fabricant1
  # ---------------------------------------------------------------------------
  - Name: Fabricant1
    Domain: fabricant1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # Fabricant2
  # ---------------------------------------------------------------------------
  - Name: Fabricant2
    Domain: fabricant2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # Fabricant3
  # ---------------------------------------------------------------------------
  - Name: Fabricant3
    Domain: fabricant3.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # CloudProvider1
  # ---------------------------------------------------------------------------
  - Name: CloudProvider1
    Domain: cloudprovider1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # CloudProvider2
  # ---------------------------------------------------------------------------
  - Name: CloudProvider2
    Domain: cloudprovider2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # CloudProvider3
  # ---------------------------------------------------------------------------
  - Name: CloudProvider3
    Domain: cloudprovider3.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

  # ---------------------------------------------------------------------------
  # Enqueteur
  # ---------------------------------------------------------------------------
  - Name: Enqueteur
    Domain: enqueteur.example.com
    EnableNodeOUs: true
    Template:
      Count: 1  # Un seul peer : peer0
      SANS:
        - localhost
    Users:
      Count: 1  # Un admin et un utilisateur

